version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0
workflows:
  version: 2.1
  nuxt-ecr-push:
    jobs:
      - aws-ecr/build-and-push-image:
          name: rails-build-and-push-image
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: 'kiku-alias/docker_byt'
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - rails-build-and-push-image
          family: 'byt-template2'
          service-name: 'byt-service'
          cluster-name: 'byt-cluster'
          container-image-name-updates: "container=byt-container,tag=${CIRCLE_SHA1}"
          
